### ISSUE TITLE
2个item之间存在一个镂空的区域

### ISSUE THREAD

**Issue by kinghom** [kareluo/PopupMenuView#1]
如果背景是白色可能认为是分割线，但是背景有文字，效果很难看，把镂空的区域设置为分割线更好

**Comment by minetsh** [comment]
这个是和iOS一样的，间隔是镂空的。如果不想要透明效果加一个背景就行了。

**Comment by kinghom** [comment]
感谢回复，请问在哪里可以设置背景，还有item宽度，我尝试在style设置，好像没有效果

**Comment by minetsh** [comment]
Demo里面有个自定义样式的，可以参考那个自定义一个Style。
